[2023-12-26T04:34:39.584+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: potential_customers_process.is_api_available manual__2023-12-26T04:34:37.124564+00:00 [queued]>
[2023-12-26T04:34:39.591+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: potential_customers_process.is_api_available manual__2023-12-26T04:34:37.124564+00:00 [queued]>
[2023-12-26T04:34:39.591+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T04:34:39.591+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-26T04:34:39.592+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-26T04:34:39.599+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-12-26 04:34:37.124564+00:00
[2023-12-26T04:34:39.603+0000] {standard_task_runner.py:55} INFO - Started process 27557 to run task
[2023-12-26T04:34:39.607+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'potential_customers_process', 'is_api_available', 'manual__2023-12-26T04:34:37.124564+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/potential_customers_process.py', '--cfg-path', '/tmp/tmpp7wkn09o']
[2023-12-26T04:34:39.609+0000] {standard_task_runner.py:83} INFO - Job 87: Subtask is_api_available
[2023-12-26T04:34:39.654+0000] {task_command.py:376} INFO - Running <TaskInstance: potential_customers_process.is_api_available manual__2023-12-26T04:34:37.124564+00:00 [running]> on host 2d20203c1be8
[2023-12-26T04:34:39.697+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=potential_customers_process
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-12-26T04:34:37.124564+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-26T04:34:37.124564+00:00
[2023-12-26T04:34:39.698+0000] {http.py:120} INFO - Poking: api/
[2023-12-26T04:34:39.705+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-12-26T04:34:39.707+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-12-26T04:34:40.181+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-12-26T04:34:40.232+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=potential_customers_process, task_id=is_api_available, execution_date=20231226T043437, start_date=20231226T043439, end_date=20231226T043440
[2023-12-26T04:34:40.305+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-12-26T04:34:40.328+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
