[2023-12-28T02:54:26.164+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: salesforce_contact_processing.is_api_available scheduled__2023-12-27T00:00:00+00:00 [queued]>
[2023-12-28T02:54:26.184+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: salesforce_contact_processing.is_api_available scheduled__2023-12-27T00:00:00+00:00 [queued]>
[2023-12-28T02:54:26.184+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-28T02:54:26.185+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-28T02:54:26.185+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-28T02:54:26.196+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-12-27 00:00:00+00:00
[2023-12-28T02:54:26.202+0000] {standard_task_runner.py:55} INFO - Started process 31913 to run task
[2023-12-28T02:54:26.205+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'salesforce_contact_processing', 'is_api_available', 'scheduled__2023-12-27T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/salesforce_contact_processing.py', '--cfg-path', '/tmp/tmpm3f_t2h1']
[2023-12-28T02:54:26.207+0000] {standard_task_runner.py:83} INFO - Job 53: Subtask is_api_available
[2023-12-28T02:54:26.249+0000] {task_command.py:376} INFO - Running <TaskInstance: salesforce_contact_processing.is_api_available scheduled__2023-12-27T00:00:00+00:00 [running]> on host bbee0f1e1252
[2023-12-28T02:54:26.293+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=salesforce_contact_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-12-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-27T00:00:00+00:00
[2023-12-28T02:54:26.294+0000] {http.py:120} INFO - Poking: 
[2023-12-28T02:54:26.303+0000] {base.py:71} INFO - Using connection ID 'salesforce' for task execution.
[2023-12-28T02:54:26.307+0000] {http.py:148} INFO - Sending 'GET' to url: https://codelink-dev-ed.develop.my.salesforce.com/services/data/
[2023-12-28T02:54:26.820+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-12-28T02:54:26.836+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=salesforce_contact_processing, task_id=is_api_available, execution_date=20231227T000000, start_date=20231228T025426, end_date=20231228T025426
[2023-12-28T02:54:26.868+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-12-28T02:54:26.903+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
