[2023-12-28T02:54:27.978+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: salesforce_contact_processing.create_table __airflow_temporary_run_2023-12-28T02:54:27.328323+00:00__ [queued]>
[2023-12-28T02:54:27.983+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: salesforce_contact_processing.create_table __airflow_temporary_run_2023-12-28T02:54:27.328323+00:00__ [queued]>
[2023-12-28T02:54:27.983+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-28T02:54:27.983+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-12-28T02:54:27.984+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-28T02:54:27.991+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2022-01-01 00:00:00+00:00
[2023-12-28T02:54:27.995+0000] {standard_task_runner.py:55} INFO - Started process 31920 to run task
[2023-12-28T02:54:27.998+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'salesforce_contact_processing', 'create_table', '__***_temporary_run_2023-12-28T02:54:27.328323+00:00__', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/salesforce_contact_processing.py', '--cfg-path', '/tmp/tmp5ni66q7f']
[2023-12-28T02:54:27.999+0000] {standard_task_runner.py:83} INFO - Job 54: Subtask create_table
[2023-12-28T02:54:28.080+0000] {task_command.py:376} INFO - Running <TaskInstance: salesforce_contact_processing.create_table __airflow_temporary_run_2023-12-28T02:54:27.328323+00:00__ [running]> on host bbee0f1e1252
[2023-12-28T02:54:28.186+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=salesforce_contact_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2023-12-28T02:54:27.328323+00:00__
[2023-12-28T02:54:28.201+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2023-12-28T02:54:28.209+0000] {sql.py:315} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS contacts (
                name TEXT NOT NULL,
                title TEXT NOT NULL,
                department TEXT NOT NULL,
                email TEXT NOT NULL,
                gender TEXT NOT NULL
            );
        , parameters: None
[2023-12-28T02:54:28.210+0000] {postgres.py:96} INFO - NOTICE:  relation "contacts" already exists, skipping

[2023-12-28T02:54:28.221+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=salesforce_contact_processing, task_id=create_table, execution_date=20220101T000000, start_date=20231228T025427, end_date=20231228T025428
[2023-12-28T02:54:28.253+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-12-28T02:54:28.381+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
